### ISSUE TITLE
DROL-RPN only run 43.5 in VOT2018

### ISSUE THREAD

**Issue by xxAna** [shallowtoil/DROL#5]
你好，谢谢你的工作和分享。我最近在跑实验的时候发现，用你的代码跑DROL-RPN只能在VOT18上达到43.6呢，请问这是什么原因呢？

**Comment by xxAna** [comment]
我用的pysot的siamrpn_r50_l234_dwxcorr这个模型以及siamrpn_r50_l234_dwxcorr_vot这里的配置文件，请问是这么配置的吗？

**Comment by jensenzhoujh** [comment]
Hi, sorry for the late reply. 

Yes, the configuration is correct. You should try to adjust the hyperparamters, including but not limited to window influence, penalty k, and fusion weight, etc.  We observe different envs and machines induce different results due to the randomness of online classsifier. But after tuning hp_params, the best result should reach in the close region of what the paper reports.

**Comment by laisimiao** [comment]
Could you please give us your hyperparamters that can reproduce the results as in paper?
